[package]
name = "rs-vless"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
tls = { path = "crates/tls" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }

[workspace]
members = [".", "crates/*"]
